import pandas as pd
import io

data = """proposal_with_date,organization_name,organization_description,date,country,iso3,iso2,hdi_category,details,original_proposed_value,original_currency_name,original_currency_iso,average_value,usd_proposed_value,usd_conversion_date,value_units,environmental_units,methodologies_used,calculation_scope,is_range,
International Foundation for Valuing Impacts (Apr 2024),International Foundation for Valuing Impacts,A non-profit organization working to standardize impact valuation.,2024-04-01,United States,USA,US,Very High,Proposed a standardized approach for companies to report GHG emissions monetarily.,$236,US dollars,USD,236,236,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Standardized impact valuation,Social Cost of Carbon,0,
EPA (Final Report) (Dec 2023),Environmental Protection Agency,The primary federal agency responsible for environmental protection.,2023-12-01,United States,USA,US,Very High,Updated SCC values using advanced methodologies and lower discount rates.,$120-$340,US dollars,USD,216,230,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Advanced methodologies,Social Cost of Carbon,1,
U.S. EPA (Updated Proposal) (Dec 2023),Environmental Protection Agency,The primary federal agency responsible for environmental protection.,2023-12-01,United States,USA,US,Very High,"Finalized updated SCC values, reflecting significant increases based on best science.",$190,US dollars,USD,190,190,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Best available science,Social Cost of Carbon,0,
UC Davis (July 2023),University of California, Davis,2023-07-01,United States,USA,US,Very High,Equity-weighted SCC emphasizing climate damages and uncertainty.,$283,US dollars,USD,283,283,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,tons of carbon dioxide equivalents,Social Cost of Carbon,0,
IMF (Jan 2023),International Monetary Fund,An international organization promoting global financial stability.,2023-01-01,United States,USA,US,Very High,Proposed international carbon price floor based on income levels of countries.,$15-$50,US dollars,USD,32.5,32.5,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Income-based carbon price floor,Carbon Pricing,1,
New York State Agencies (Jan 2021),New York State Agencies,Various state agencies working on climate policy.,2021-01-01,United States,USA,US,Very High,Guidance under Climate Leadership Act to reduce emissions and achieve net-zero.,$125,US dollars,USD,125,125,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Climate Leadership Act guidance,Social Cost of Carbon,0,
Biden Administration (IWG Interim Update) (Feb 2021),Biden Administration Interagency Working Group,A temporary group that develops guidance for federal agencies.,2021-02-01,United States,USA,US,Very High,Interim update reinstating Obama-era methodology with adjustments.,$51,US dollars,USD,51,51,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Obama-era methodology with adjustments,Social Cost of Carbon,0,
Trump Administration (Oct 2017),Trump Administration,The executive branch of the US Federal government under Donald Trump.,2017-10-01,United States,USA,US,Very High,Lowered SCC estimates focusing on domestic impacts with higher discount rates.,$3-$5,US dollars,USD,4,4,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Domestic impacts,Social Cost of Carbon,1,
Climate Leadership Council (Feb 2017),Climate Leadership Council,A coalition advocating for a carbon dividends plan.,2017-02-01,United States,USA,US,Very High,"Carbon dividends plan starting at $40/ton, increasing annually by 5% above inflation.",$40-$50,US dollars,USD,45,45,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Carbon dividends plan,Carbon Pricing,1,
Obama Administration (IWG Update) (Nov 2013),Obama Administration Interagency Working Group,A temporary group that develops guidance for federal agencies.,2013-11-01,United States,USA,US,Very High,Updated SCC values for regulatory impact analyses under federal guidelines.,$37,US dollars,USD,37,37,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Updated SCC methodology,Social Cost of Carbon,0,
UK Government Economic Service (2002-01-01),UK Government Economic Service,The professional body of economists in the UK Civil Service.,2002-01-01,United Kingdom,GBR,GB,Very High,Recommended illustrative SCC range for policy appraisal across government sectors.,£35-£140,British pounds,GBP,112.8,109.475,2024-11-20,pounds per ton CO2e,tons of carbon dioxide equivalents,Illustrative SCC range,Social Cost of Carbon,1,
Stern Review (Oct 2006),Stern Review,A landmark report on the economics of climate change.,2006-10-01,United Kingdom,GBR,GB,Very High,Early influential report advocating for strong climate action.,~$85,US dollars,USD,85,85,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Economic modeling,Social Cost of Carbon,0,
Canada Government (Aug 2023),Government of Canada,The federal government of Canada.,2023-08-01,Canada,CAN,CA,Very High,The Federal Carbon Price was increased to CAD$65 per tonne CO2e in 2023.,CAD$65,Canadian dollars,CAD,48,48.01,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Federal carbon pricing,Carbon Pricing,0,
French Government - Quinet Report (2019-01-01),French Government,The government of France.,2019-01-01,France,FRA,FR,Very High,"Recommended range for the SCC with a central value around 250 Euros per tonne CO2e by 2030, rising steeply after that.",€250-€770,Euros,EUR,420,555.14,2024-11-20,euros per ton CO2e,tons of carbon dioxide equivalents,SCC range with projected increase,Social Cost of Carbon,1,
Nordhaus DICE Model (2017),Yale University,Integrated assessment model of climate change and economics.,2017-01-01,United States,USA,US,Very High,Highly influential integrated assessment model for climate policy.,$31,US dollars,USD,31,31,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Integrated assessment modeling,Social Cost of Carbon,0,
RFF (2021),Resources for the Future,Independent research institution focusing on environmental and natural resource issues.,2021-01-01,United States,USA,US,Very High,Research and analysis on the social cost of carbon.,$51,US dollars,USD,51,51,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,SCC modeling analysis,Social Cost of Carbon,0,
IPCC (AR6 Synthesis Report) (2023),Intergovernmental Panel on Climate Change,The leading international body for assessing climate change.,2023-01-01,Switzerland,CHE,CH,Very High,Synthesis of scientific literature on climate change, including the SCC.,Not Applicable,Not Applicable,Not Applicable,Varies,2024-11-20,,dollars per ton CO2e,tons of carbon dioxide equivalents,Synthesis of scientific literature,0,
FUND Model (2019),University College London,A climate economy model.,2019-01-01,United Kingdom,GBR,GB,Very High,Climate economy model focused on policy evaluation.,$25-$60,US dollars,USD,42.5,42.5,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Climate economy modeling,Social Cost of Carbon,1,
PAGE Model (2019),Cambridge University,Policy Analysis model of climate damages.,2019-01-01,United Kingdom,GBR,GB,Very High,Policy Analysis model for Social Cost of Carbon.,$100-$200,US dollars,USD,150,150,2024-11-20,dollars per ton CO2e,tons of carbon dioxide equivalents,Policy Analysis Modeling,Social Cost of Carbon,1,
"""

df = pd.read_csv(io.StringIO(data))

# Rename the column
df.rename(columns={'usd_proposed_value': 'Standardized Proposal USD'}, inplace=True)

# Create the new column
df['Standardized Proposal USD_MTC02E'] = df['Standardized Proposal USD'] * 1000000

print(df.to_markdown(index=False))